### ISSUE TITLE
非常棒的创意,请添加分享文件/文件夹功能

### ISSUE THREAD

**Issue by youxia2016** [wusuopu/baidu-pan-cli#2]
非常棒的创意，类似Aria2可通过http协议调用，但是缺少我最喜爱的分享功能，(分享时间可选1天 7天 永久)请添加下，谢谢

**Comment by wusuopu** [comment]
@youxia2016 文件分享的话，直接在百度网盘的界面上进行操作不了可以了吗？为什么还要通过命令行来操作呢？

**Comment by youxia2016** [comment]
比如我一个文件夹需要分享30天，但是官方仅提供7天和1天，我这边做一个服务器，每隔7天 自动再分享一次，服务器无法操作百度网盘界面，仅能通过API的形式进行操作

**Comment by youxia2016** [comment]
我一个文件/文件夹需要分享30天 4个7天和2个1天，这样组合进行分配，只有类似API或命令行才可以自动，通过网盘界面需要手动，不能批量管理，而且还会出错，但是如果服务器进行自动处理，就不会出错了

**Comment by youxia2016** [comment]
我想百度网盘不希望我们这样做，我仅分享了不到30个7日链接，就提示我分享太多，24小时后 再进行操作，不能分享了
